import { StateImpactSnapshot } from '../../types/government';
import {
  ArrowRight,
  Sparkles,
  Globe2,
  Activity,
  BookOpen,
  TrendingUp,
  ShieldCheck,
} from 'lucide-react';
import { Link } from 'react-router-dom';

interface StateImpactSnapshotBandProps {
  impact: StateImpactSnapshot;
}

export function StateImpactSnapshotBand({ impact }: StateImpactSnapshotBandProps) {
  const cards = [
    {
      value: impact.potentialBeneficiaries,
      label: 'Potential Beneficiaries',
      subtext: 'Direct household coverage in tribal blocks',
      icon: Globe2,
      accent: 'text-[#FA7E61]',
    },
    {
      value: impact.activeFieldLocations.toString(),
      label: 'Active Field Locations',
      subtext: 'Villages & mining wards with live hardware',
      icon: Activity,
      accent: 'text-[#F5A623]',
    },
    {
      value: impact.researchOutputs.toString(),
      label: 'Research Outputs',
      subtext: 'Peer-reviewed papers, patents & open datasets',
      icon: BookOpen,
      accent: 'text-[#FEE1C7]',
    },
    {
      value: impact.startupTransferOpps.toString(),
      label: 'Startup / Transfer Opps',
      subtext: 'MSME commercialization licenses',
      icon: TrendingUp,
      accent: 'text-[#B5A886]',
    },
    {
      value: impact.projectsInVerification.toString(),
      label: 'Projects in Verification',
      subtext: 'Entering state policy scale-up audit',
      icon: ShieldCheck,
      accent: 'text-[#15803D]',
    },
  ];

  return (
    <section className="bg-[#4C1E4F] text-white py-14 sm:py-18 rounded-3xl relative overflow-hidden border border-[#3A143D] text-left">
      {/* Background Topographic Matrix */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 opacity-[0.04] pattern-topography"
      />

      <div className="mx-auto max-w-7xl px-6 sm:px-10 relative z-10 space-y-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-white/15 pb-6">
          <div className="space-y-2 max-w-2xl">
            <div className="inline-flex items-center gap-2 text-[11px] font-mono uppercase tracking-widest text-[#FA7E61] font-bold">
              <Sparkles className="h-4 w-4" />
              <span>DIRECTORATE IMPACT AUDIT</span>
            </div>
            <h3 className="text-[2rem] sm:text-[2.6rem] font-extrabold text-white tracking-tight leading-tight font-sans">
              State Innovation Impact Snapshot
            </h3>
            <p className="text-[15px] text-[#FEE1C7]/80 leading-relaxed">
              Evaluating real-world outcomes generated by collaborative projects across
              Jharkhand&apos;s districts.
            </p>
          </div>

          <div className="space-y-2 shrink-0">
            <div className="text-[10px] font-mono text-[#FEE1C7]/60 uppercase tracking-widest text-right">
              PROTOTYPE AUDIT · DEMO DATA
            </div>
            <Link
              to="/impact"
              className="inline-flex items-center gap-2 rounded-xl bg-[#FA7E61] hover:bg-[#e86c4f] text-white px-6 py-3 text-[13.5px] font-bold shadow-md transition-all active:scale-[0.98]"
            >
              <span>View Detailed Impact</span>
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>

        {/* 5 Impact Metrics Grid */}
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3.5">
          {cards.map((card) => {
            const Icon = card.icon;
            return (
              <div
                key={card.label}
                className="p-5 rounded-2xl bg-white/5 border border-white/10 hover:border-white/20 transition-all space-y-3 backdrop-blur-xs flex flex-col justify-between"
              >
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <Icon className={`h-4 w-4 ${card.accent}`} />
                  </div>

                  <div
                    className={`text-[2rem] sm:text-[2.4rem] font-extrabold font-mono tracking-tight leading-none ${card.accent}`}
                  >
                    {card.value}
                  </div>

                  <div className="text-[13.5px] font-bold text-white leading-snug">
                    {card.label}
                  </div>
                </div>

                <div className="text-[11px] text-[#FEE1C7]/60 font-mono pt-2 border-t border-white/10 leading-tight">
                  {card.subtext}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
